apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: {{CLUSTER_NAME}}
  region: {{REGION}}

iam:
  withOIDC: true

managedNodeGroups:
  - name: {{NODEGROUP_NAME}}
    instanceType: {{INSTANCE_TYPE}}
    desiredCapacity: 1
    minSize: 1
    maxSize: 3
    volumeSize: 20
    spot: true
