apiVersion: batch/v1
kind: Job
metadata:
  name: load-generator
spec:
  template:
    spec:
      containers:
      - name: hey
        image: curlimages/curl
        command: ["/bin/sh", "-c"]
        args:
          - |
            while true; do
              curl -s http://cpu-demo:8080/start
              sleep 1
            done
      restartPolicy: Never
