apiVersion: v1
kind: Service
metadata:
  name: cluster-autoscaler-metrics
  namespace: kube-system
  labels:
    app.kubernetes.io/name: aws-cluster-autoscaler
spec:
  ports:
  - name: metrics
    port: 8085
    targetPort: 8085
  selector:
    app.kubernetes.io/name: aws-cluster-autoscaler
